### ISSUE TITLE
Doc for Scenario management controls

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-doc#662]
[Core elements](https://docs.taipy.io/en/develop/manuals/gui/viselements/controls/#scenario-management-controls)

- [x] Scenario Selector [Details](https://docs.taipy.io/en/develop/manuals/gui/corelements/scenario_selector/#details)
  - figcaption is wrong : "No scenario to select"
- [x] Scenario 
  - [Properties](https://docs.taipy.io/en/develop/manuals/gui/corelements/scenario/#properties)
    - show_tags default value is True (will push a new viselements.json)
  - [Details](https://docs.taipy.io/en/develop/manuals/gui/corelements/scenario/#details)
    - manque les tags (show_tags default = True)
- [x] Datanode Selector [Details](https://docs.taipy.io/en/develop/manuals/gui/corelements/data_node_selector/#details)
  - figure is not up to date (show pins)
  - [with pins](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9259c61aa824bf3106b0ba70ec4d709a35c9c6b/image.png)
- [x] Data_node [Details](https://docs.taipy.io/en/develop/manuals/gui/corelements/data_node/#details)
[viewer](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d81ea1620f090b373bd295bd7c0d54cdaf8b3952/image.png)
- [x] Job_selector [Details](https://docs.taipy.io/en/develop/manuals/gui/corelements/job_selector/#details)
[Selector](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d06e7cbc4b00f940e3119032e5caa99f8132d341/image.png)

**Comment by FredLL-Avaiga** [comment]
an app that shows the different controls
```
from src.taipy.gui_core._GuiCoreLib import _GuiCore

from taipy import Config, Scope, Frequency

import datetime as dt

import taipy as tp
import pandas as pd

PATH_CSV = "dataset.csv"
PATH_PARQUET = "dataset.parquet"


def transform(csv, parquet, pickle):
    print("     Cleaning data")
    return csv, 5, "hello", dt.datetime.now()


## Input Data csv
csv_cfg = Config.configure_data_node(id="csv", storage_type="csv", path=PATH_CSV)  # scope=Scope.GLOBAL,
parquet_cfg = Config.configure_data_node(id="parquet", scope=Scope.CYCLE, storage_type="parquet", path=PATH_PARQUET)
pickle_cfg = Config.configure_data_node(id="pickle")


## Remaining Data Node
data_out_cfg = Config.configure_data_node(id="data_out")
int_cfg = Config.configure_data_node(id="int")
string_cfg = Config.configure_data_node(id="string")
date_cfg = Config.configure_data_node(id="date")

# Task config objects
transform_task_cfg = Config.configure_task(
    id="transform",
    function=transform,
    input=[csv_cfg, parquet_cfg, pickle_cfg],
    output=[data_out_cfg, int_cfg, string_cfg, date_cfg],
    skippable=True,
)


# Configure our scenario config.
scenario_cfg = Config.configure_scenario(id="scenario", task_configs=[transform_task_cfg], frequency=Frequency.MONTHLY)

scenario = None
data_node = None

jobs = []

chart_configs = {"dvs": {"types": ["pie"]}, "csv": {"types": ["scatter", "scatter"], "traces": [["World", "Hi"], ["Unnamed: 0", "World"]], "cumulative": True}}

page = """
# Jobs
<|{jobs}|job_selector|>

# Scenarios
<|1 4|layout|
<|{scenario}|scenario_selector|>

<|{scenario}|scenario|>
<|{scenario}|scenario_dag|>
|>

# Data Nodes
<|1 4|layout|
<|{data_node}|data_node_selector|>

<|{data_node}|data_node|chart_configs={chart_configs}|>
|>

# Int from chosen scenario
<|{scenario.int if scenario else None}|data_node|scenario={scenario}|>
"""

pages = {"/": "<|navbar|> <|toggle|theme|> <br/>", "Data-Node": page}


if __name__ == "__main__":
    tp.Core().run()

    scenario = tp.create_scenario(config=scenario_cfg)
    data_pickle = pd.DataFrame({"Hello": [1, 2, 3], "World": [4, 5, 6]})
    scenario.pickle.write(data_pickle, comment="init")
    data_csv = pd.DataFrame(
        {
            "Hi": ["red", "step", "true"],
            "World": [None, 5, 6],
            "Hi1": ["red", "step", "true"],
            "World1": [None, 5, 6],
            "Hi2": ["red", "step", "true"],
            "World2": [None, 5, 6],
            "Hi3": ["red", "step", "true"],
            "World3": [None, 5, 6],
            "Hi4": ["red", "step", "true"],
            "World4": [None, 5, 6],
            "Hi5": ["red", "step", "true"],
            "World5": [None, 5, 6],
        }
    )
    data_csv.to_csv(PATH_CSV)
    data_parquet = pd.DataFrame(
        {"Date": [dt.datetime(2021, 1, 1), dt.datetime(2021, 1, 2), dt.datetime(2021, 1, 3)], "Value": [1, 2, 3]}
    )
    data_parquet.to_parquet(PATH_PARQUET)

    print(scenario.pickle.read())

    # [tp.create_scenario(config=scenario_cfg, name=f"scenario_{i}") for i in range(30)]
    # [scenario.pickle.write(data_pickle) for scenario in tp.get_scenarios()]
    # [scenario.submit() for scenario in tp.get_scenarios()]

    tp.Gui(pages=pages).run(debug=True)

```
